DROP TABLE IF EXISTS dada;

CREATE TABLE dada (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filename TEXT NOT NULL,
    content TEXT NOT NULL
);
